"""API routes for Phase 7 Cross-Source Field Conflicts.

Exposes endpoints for querying field conflict records generated by ValidationAgent.
"""

from typing import List, Optional
from uuid import UUID
from fastapi import APIRouter, HTTPException

from ..db.store import store
from ..models.schemas import FieldConflict
from ..utils.logging import get_logger

logger = get_logger("routes_conflicts")
router = APIRouter(prefix="/api", tags=["conflicts"])


@router.get("/conflicts", response_model=List[FieldConflict])
async def list_all_conflicts(product_id: Optional[UUID] = None):
    """Retrieve all cross-source field conflicts, optionally filtered by product_id."""
    return store.list_field_conflicts(product_id=product_id)


@router.get("/products/{product_id}/conflicts", response_model=List[FieldConflict])
async def get_product_conflicts(product_id: UUID):
    """Retrieve all cross-source field conflicts for a specific product."""
    conflicts = store.list_field_conflicts(product_id=product_id)
    return conflicts
